# Generated by Django 4.2.6 on 2023-12-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("filmsapp", "0002_movie_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddMovie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("desc", models.TextField()),
                ("img", models.ImageField(upload_to="gallery")),
            ],
        ),
    ]
